server:
  port: 1003
spring:
  application:
    name: ssa
eureka:
  client:
    service-url:
      defaultZone: http://43.205.101.87:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'